In [1]:




a = (1,2)
print(type(a))

<class 'tuple'>


In [ ]:
answer = [(0,1),(1,2)]

In [3]:
(0,1) in answer

True

In [7]:
grid_set = set()
for i in range(5):
    for j in range(5):
        grid_set.add((i,j))
        

In [9]:
len(grid_set)

25

In [11]:
(1,2) in grid_set

True

In [12]:
grid_set.remove((1,2))

In [13]:
(1,2) in grid_set

False

In [17]:

start = (0,0)


path = []

def recursion(x, y,grid_set):
    
    if(len(grid_set) == 0):
        
        return [(x,y)]
    
    
    
    if((x+1,y+2) in grid_set):
        grid_set.remove((x+1,y+2,))
        if(recursion(x+1, y+2,grid_set)==False):
            return False
        else:
            return recursion(x+1, y+2,grid_set).append((x,y))
        
        
    if...
    
    
    
    
    return False


In [36]:
def recursion(x, y,grid_set):
    print((x,y))
    print(grid_set)
    if(len(grid_set) == 0):
        return [(x,y)]
    if[(x,y),grid_set] in fail_set:
        return False
    
    # 1 2 
    if(((x+1,y+2) in grid_set) and recursion(x+1, y+2,grid_set)!=False):
        print("###")
        grid_set.remove((x+1,y+2))
        return recursion(x+1,y+2,grid_set).append((x,y))
         
    # 1 -2 
    if(((x+1,y-2) in grid_set) and recursion(x+1, y-2,grid_set)!=False):
        grid_set.remove((x+1,y-2))
        return recursion(x+1,y-2,grid_set).append((x,y))
    # -1 2
    if(((x-1,y+2) in grid_set) and recursion(x-1, y+2,grid_set)!=False):
        grid_set.remove((x-1,y+2))
        return recursion(x-1,y+2,grid_set).append((x,y))
        
    # -1 -2
    if(((x-1,y-2) in grid_set) and recursion(x-1, y-2,grid_set)!=False):
        grid_set.remove((x-1,y-2))
        return recursion(x-1,y-2,grid_set).append((x,y))

    #  2 1
    if(((x+2,y+1) in grid_set) and recursion(x+2, y+1,grid_set)!=False):
        grid_set.remove((x+2,y+1))
        return recursion(x+2,y+1,grid_set).append((x,y))

    #  2 -1
    if(((x+2,y-1) in grid_set) and recursion(x+2, y-1,grid_set)!=False):
        grid_set.remove((x+2,y-1))
        return recursion(x+2,y-1,grid_set).append((x,y))

    #  -2 1
    if(((x-2,y+1) in grid_set) and recursion(x-2, y+1,grid_set)!=False):
        grid_set.remove((x-2,y+1))
        return recursion(x-2,y+1,grid_set).append((x,y))

    #  -2 -1
    if(((x-2,y-1) in grid_set) and recursion(x-2, y-1,grid_set)!=False):
        grid_set.remove((x-2,y-1))
        return recursion(x-2,y-1,grid_set).append((x,y))

    fail_set.append([(x,y),grid_set])
    return False

In [37]:
grid_set = set()
fail_set = []
for i in range(5):
    for j in range(5):
        grid_set.add((i,j))

x = 0
y = 0
ml = recursion(x, y,grid_set)

(0, 0)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(1, 2)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(2, 4)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(3, 2)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(4, 4)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), 

{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(4, 4)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(3, 2)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(4, 4)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(3, 2)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1),

(3, 2)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(4, 4)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(3, 2)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(4, 4)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(3, 2)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), 

RecursionError: maximum recursion depth exceeded while calling a Python object

In [34]:
a ={(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}

In [35]:
len(a)

25

In [52]:
def recursion(x, y,grid_set):
    print((x,y))
    print(grid_set)
    if(len(grid_set) == 0):
        return [(x,y)]
    #if[(x,y),grid_set] in fail_set:
        #return []
    
    # 1 2 
    if((x+1,y+2) in grid_set):
        print("###")
        grid_set.remove((x+1,y+2))
        return recursion(x+1,y+2,grid_set).append((x,y))
         
    # 1 -2 
    if((x+1,y-2) in grid_set):
        grid_set.remove((x+1,y-2))
        return recursion(x+1,y-2,grid_set).append((x,y))
    # -1 2
    if((x-1,y+2) in grid_set):
        grid_set.remove((x-1,y+2))
        return recursion(x-1,y+2,grid_set).append((x,y))
        
    # -1 -2
    if((x-1,y-2) in grid_set):
        grid_set.remove((x-1,y-2))
        return recursion(x-1,y-2,grid_set).append((x,y))

    #  2 1
    if((x+2,y+1) in grid_set):
        grid_set.remove((x+2,y+1))
        return recursion(x+2,y+1,grid_set).append((x,y))

    #  2 -1
    if((x+2,y-1) in grid_set):
        grid_set.remove((x+2,y-1))
        return recursion(x+2,y-1,grid_set).append((x,y))

    #  -2 1
    if((x-2,y+1) in grid_set):
        grid_set.remove((x-2,y+1))
        return recursion(x-2,y+1,grid_set).append((x,y))

    #  -2 -1
    if((x-2,y-1) in grid_set):
        grid_set.remove((x-2,y-1))
        return recursion(x-2,y-1,grid_set).append((x,y))

    #fail_set.append([(x,y),grid_set])
    print("final")
    return []

In [53]:
grid_set = set()
fail_set = []
for i in range(5):
    for j in range(5):
        grid_set.add((i,j))

x = 0
y = 0
ml = recursion(x, y,grid_set)

(0, 0)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (1, 2), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
###
(1, 2)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (2, 4), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
###
(2, 4)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (0, 4), (2, 1), (3, 2), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(3, 2)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (0, 4), (2, 1), (4, 1), (4, 4), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
###
(4, 4)
{(4, 0), (3, 4), (4, 3), (3, 1), (0, 2), (2, 2), (1, 0), (1, 3), (4, 2), (3, 0), (3, 3), (0, 1), (0, 4), (2, 1), (4, 1), (0, 0), (1, 1), (0, 3), (2, 0), (1, 4), (2, 3)}
(2, 3)
{(4, 0), (3, 4), (4, 

AttributeError: 'NoneType' object has no attribute 'append'

In [50]:
def test1():
    return []


a = test1()
a.append((1,2))

In [51]:
a

[(1, 2)]

In [62]:
import numpy as np

move_x = [2, 1, -1, -2, -2, -1, 1, 2]
move_y = [1, 2, 2, 1, -1, -2, -2, -1]

def validateMove(bo, row, col):
    if row < 8 and row >= 0 and col < 8 and col >= 0 and bo[row, col] == 0:
        return True
    else:
        return False

def solve (bo, row, col, counter):
    if counter >= 65:
            return True
        
    for i in range(8):
        
        new_x = row + move_x[i]
        new_y = col + move_y[i]
        if validateMove(bo, new_x, new_y):
            bo[new_x,new_y] = counter
            if solve(bo,new_x, new_y, counter+1):
                return True
            bo[new_x,new_y] = 0
    return False

board = np.zeros((8, 8))

board[3,2] = 1
solve(board,3,2,2)
print(board.sum())
print(board)

2080.0
[[38. 53. 30. 57. 14. 63. 28.  7.]
 [31. 58. 39. 62. 29.  8. 13. 64.]
 [52. 37. 54. 25. 56. 15.  6. 27.]
 [59. 32.  1. 40. 61. 26.  9. 12.]
 [36. 51. 60. 55. 24. 11. 16.  5.]
 [45. 48. 33.  2. 41. 18. 21. 10.]
 [50. 35. 46. 43. 20. 23.  4. 17.]
 [47. 44. 49. 34.  3. 42. 19. 22.]]


In [55]:
(1+64)*64/2

2080.0